# General Jekyll Config
#highlighter: pygments

name: Miscellaneous Bits
description: A technical blog on Elixir, Ruby and other topics
url: http://blog.danielberkompas.com
author:
  name: Daniel Berkompas
  url: http://danielberkompas.com
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
gems:
  - jekyll-feed
feed:
  path: atom.xml
